development:
  password: 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
  theme_id: "118034006174"
  store: christiandp7.myshopify.com
  #proxy: http://localhost:8000
  ignore_files: 
  - config/settings_data.json